version: '3.8'

services:
  db:
    image: bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
    ports:
      - '5432:5432'
    volumes:
      - my-db-data:/var/lib/postgresql/data

volumes:
  my-db-data:
